### ISSUE TITLE
Crashes when opening inventory screen in survival with Trinkets

### ISSUE THREAD

**Issue by Samekichi** [camas/inv-trash-slot#2]
When loaded together with [Trinkets](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric), the game will crash after opening inventory GUI in survival mode. 
(A full crash report can be found [here](https://pastebin.com/4Ep8nCtW). )

**Comment by camas** [comment]
Created a pull request for Trinkets that should fix the issue.
