### ISSUE TITLE
Survival Inventory visual glitch (Creative Mode)

### ISSUE THREAD

**Issue by Fourmisain** [camas/inv-trash-slot#3]
I put 37 Stone Buttons in my trash slot while in Survival Mode and currently have a Redstone Dust in my 2nd slot.
After changing to Creative Mode and opening the Survival Inventory it looks like this:
![visual glitch](https://user-images.githubusercontent.com/8464472/96770049-47045380-13e0-11eb-863e-a7a902619869.png)
The buttons are not interactible, they're not actually there, it's a purely visual glitch (the trash hotkey also does nothing).
The easiest fix is probably to disable the trash slot completely when the player is in Creative Mode as it's not really needed anyways.

I'm on Minecraft version 1.16.3 if that matters.

**Comment by Romz24** [comment]
It would be great if this is fixed, because of this bug, the creative inventory is inconvenient to use.

**Comment by camas** [comment]
Think a25c9198 fixes this

1.0.2 available on curse whenever it gets approved

**Comment by Fourmisain** [comment]
Yep, looks like it's working!
